# Generated by Django 3.2 on 2026-01-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('discription', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
